version: '3'
services:
  xiaogpt:
    image: yihong0618/xiaogpt
    command: --config=/config/config.json
    ports:
      - "9527:9527"
    environment:
      XIAOGPT_HOSTNAME: 192.168.2.110
    volumes:
      - /root/xiaogpt:/config
      - /root/xiaogpt/cookies.json:/cookies.json:ro
    deploy:
      restart_policy:
        condition: on-failure